Add location of the Mayastor Helm chart
openebs/charts pull request #177
Opened 2020-12-10 12:13 UTC by bobek

Mayastor published an initial version of its Helm chart. It is currently maintained within the same repository. This patch just adds a note to README.

(closes #168)

2020-12-10 16:22 UTC, arne-rusek requested changes

2020-12-10 16:22 UTC, arne-rusek commented on README.md
> +Helm chart for Mayastor is currently maintained [along the Mayastor code-base](https://github.com/openebs/Mayastor/tree/develop/chart). Please, note, that it is being actively maintained and can chan
```suggestion
Helm chart for Mayastor is currently maintained [along the Mayastor code-base](https://github.com/openebs/Mayastor/tree/develop/chart). Please, note, that it is being actively developed and can change without warning.
```

2020-12-10 19:36 UTC, bobek commented on README.md
> +Helm chart for Mayastor is currently maintained [along the Mayastor code-base](https://github.com/openebs/Mayastor/tree/develop/chart). Please, note, that it is being actively maintained and can chan
:facepalm: thank you!

2020-12-11 09:44 UTC, arne-rusek approved these changes

2020-12-11 09:48 UTC, arne-rusek commented
@kmova please take a look and merge if you're OK with the PR.

2020-12-13 16:00 UTC, kmova approved these changes

2020-12-13 16:02 UTC, merged