[stable/openebs]: update openebs chart to use 0.8.0 version of NFS
openebs/charts pull request #293
Opened 2021-11-11 13:41 UTC by mittachaitu

Signed-off-by: mittachaitu <sai.chaithanya@mayadata.io>

#### Why is this change required?

This PR updates the openebs chart to use 0.8.0 version of
Dynamic-NFS provisioner

#### What is changed?
- Updates Char.yaml and values.yaml to point to latest version of NFS

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/openebs/charts/blob/HEAD/CONTRIBUTING.md#sign-your-commits) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

2021-11-23 06:44 UTC, mynktl approved these changes

2021-11-25 17:33 UTC, kmova commented
@mittachaitu  -- this one looks good. Can you also raise a PR to update the version tags for the YAML at: 

- Update the versions at https://github.com/openebs/charts/blob/gh-pages/nfs-operator.yaml
- Create a 3.1.0 folder and include the NFS file at https://github.com/openebs/charts/tree/gh-pages/versioned

2021-11-25 17:36 UTC, kmova requested changes
While this PR can be merged, it will be good to merge this alongside the update to the corresponding YAML file as mentioned in https://github.com/openebs/charts/pull/293#issuecomment-979377904

2021-11-26 05:23 UTC, mittachaitu commented
> @mittachaitu -- this one looks good. Can you also raise a PR to update the version tags for the YAML at:
> 
>     * Update the versions at https://github.com/openebs/charts/blob/gh-pages/nfs-operator.yaml
> 
>     * Create a 3.1.0 folder and include the NFS file at https://github.com/openebs/charts/tree/gh-pages/versioned

Have raised a PR(#295 )

2021-11-26 11:57 UTC, kmova approved these changes

2021-11-26 11:57 UTC, merged